#!/usr/bin/env python3
"""Derive every published number from the records. Never assert one.

This is the file that makes the site's central claim checkable. The counts on
`/counts/` are not typed by anyone: they are recomputed here from
`data/sites/*.yml` and written to `data/counts.yml`, which CI regenerates and
compares. If a number on the site ever disagrees with the records behind it,
the build fails rather than publishing the prettier figure.

Two things it deliberately refuses to do:

  * It never emits a total across bands. Summing `fortified_residence` and
    `palatial_seat` would double-count every structure that satisfies both and
    would re-create the single global integer this project exists to reject.
  * It never merges assessed verdicts with register-derived ones. A verdict
    transcribed in bulk from a register's own typology is not the same claim as
    one somebody reached by applying the band's criterion, and a headline that
    adds them together would be a dataset reporting how many rows it copied.

  * It never fills an `open` band's count with the number of records held.
    Holding 30 records in a band that has no bounding register tells you about
    this dataset's progress, not about the world, and the two are reported in
    different fields so they cannot be confused.

Usage:
    scripts/counts.py            # rewrite data/counts.yml + coverage records_held
    scripts/counts.py --check    # exit 1 if either is stale (CI mode)
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from collections import defaultdict

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITES = ROOT / "data" / "sites"
DEFINITIONS = ROOT / "data" / "definitions.yml"
COVERAGE = ROOT / "data" / "coverage.yml"
OUT = ROOT / "data" / "counts.yml"

BANNER = (
    "# GENERATED by scripts/counts.py — do not hand-edit.\n"
    "#\n"
    "# Every integer here is derived from data/sites/*.yml at generation time.\n"
    "# CI regenerates this file and fails on drift, so a number on the site can\n"
    "# never drift from the records that justify it.\n"
    "#\n"
    "# `held` counts THIS DATASET. `population` (in data/coverage.yml) counts the\n"
    "# WORLD, per the bounding register. They are never the same field and an\n"
    "# open band never gets a population figure at all.\n"
)


def load_yaml(path: pathlib.Path):
    with path.open() as fh:
        return yaml.safe_load(fh)


def jurisdiction_of(record: dict) -> str:
    """GB + region Scotland -> GB-SCT. Falls back to the bare country code."""
    loc = record.get("location") or {}
    country = loc.get("country", "??")
    region = (loc.get("region") or "").strip().lower()
    subdivisions = {
        ("GB", "england"): "GB-ENG",
        ("GB", "scotland"): "GB-SCT",
        ("GB", "wales"): "GB-WLS",
        ("GB", "northern ireland"): "GB-NIR",
        ("DE", "saxony"): "DE-SN",
        ("DE", "sachsen"): "DE-SN",
    }
    return subdivisions.get((country, region), country)


def collect() -> tuple[dict, dict, list[str]]:
    definitions = load_yaml(DEFINITIONS)["definitions"]
    band_ids = [d["id"] for d in definitions]
    closure = {d["id"]: d["closure"] for d in definitions}

    records = [load_yaml(p) for p in sorted(SITES.glob("*.yml"))]

    # band -> verdict -> count, and band -> jurisdiction -> yes-count
    def empty():
        return {"yes": 0, "no": 0, "contested": 0}

    by_band: dict[str, dict] = {
        b: {"assessed": empty(), "register_derived": empty(), "unassessed": 0}
        for b in band_ids
    }
    by_cell: dict[tuple[str, str], int] = defaultdict(int)

    for rec in records:
        met = rec.get("definitions_met") or {}
        juris = jurisdiction_of(rec)
        for band in band_ids:
            entry = met.get(band)
            if entry is None:
                by_band[band]["unassessed"] += 1
                continue
            verdict = entry["verdict"]
            # Absent `assessment` means somebody applied the criterion; bulk
            # imports must say so explicitly.
            kind = ("register_derived"
                    if entry.get("assessment") == "register-derived" else "assessed")
            by_band[band][kind][verdict] += 1
            # A cell counts records the dataset actually holds for it, which
            # includes contested ones — a contested record is research done,
            # not research skipped.
            if verdict in ("yes", "contested"):
                by_cell[(band, juris)] += 1

    counts = {
        "version": 1,
        "records_total": len(records),
        "bands": [
            {
                "definition": band,
                "closure": closure[band],
                "held": {
                    "assessed": by_band[band]["assessed"],
                    "register_derived": by_band[band]["register_derived"],
                    "unassessed": by_band[band]["unassessed"],
                },
            }
            for band in band_ids
        ],
    }
    return counts, dict(by_cell), band_ids


def apply_coverage(by_cell: dict[tuple[str, str], int]) -> str:
    """Rewrite records_held on every coverage cell from the records."""
    coverage = load_yaml(COVERAGE)
    for cell in coverage["cells"]:
        cell["records_held"] = by_cell.get((cell["definition"], cell["jurisdiction"]), 0)
    header = (
        "# Coverage grid — one cell per (definition band x jurisdiction).\n"
        "#\n"
        "# `records_held` is GENERATED by scripts/counts.py; everything else is\n"
        "# hand-maintained and reviewed. An `unexamined` cell is a published\n"
        "# admission, and `settled_by` names the register that would close it.\n"
    )
    return header + yaml.safe_dump(coverage, sort_keys=False, allow_unicode=True, width=100)


def render_counts(counts: dict) -> str:
    return BANNER + yaml.safe_dump(counts, sort_keys=False, allow_unicode=True, width=100)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    args = ap.parse_args()

    counts, by_cell, _ = collect()
    counts_text = render_counts(counts)
    coverage_text = apply_coverage(by_cell)

    targets = [(OUT, counts_text), (COVERAGE, coverage_text)]

    if args.check:
        stale = [p.name for p, text in targets if not p.exists() or p.read_text() != text]
        if stale:
            print(
                "counts: STALE -> " + ", ".join(stale) + "\n"
                "  A published number no longer matches the records behind it.\n"
                "  Run scripts/counts.py and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"counts: fresh ({counts['records_total']} records)")
        return 0

    for path, text in targets:
        path.write_text(text)
    print(f"counts: wrote {OUT.name} + refreshed coverage ({counts['records_total']} records)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
